#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 21 17:04:57 HKT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=20
shaderPack=
enableShaders=true
